name: navtab_demo
description: "A new Flutter project."
publish_to: 'none' 
version: 1.0.0+1

environment:
  sdk: ^3.6.2

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  extended_nested_scroll_view: ^6.2.1
  google_nav_bar: ^5.0.7
  line_icons: ^2.0.3
  pull_to_refresh_flutter3: ^2.0.2
  flutter_screenutil: ^5.9.3
  styled_widget: ^0.4.1
  flutter_swiper_view: ^1.1.8
  cached_network_image: ^3.4.1
  permission_handler: ^11.3.1
  easy_refresh: ^3.4.0
  flutter_staggered_grid_view: ^0.7.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/images/
    - assets/images/grid-buttons/
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
